version: "3.3"
services:
    rabbitMQ:
        image: rabbitmq:3-management
        ports:
            # - "5672:5672"
            - "8081:15672"
            # - "1885:15675"
            - "1883:1883"
        environment:
            RABBITMQ_DEFAULT_USER: "iot"
            RABBITMQ_DEFAULT_PASS: "iotNhom8"
        command: '/bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server"'
    reactjs:
        depends_on:
            - rabbitMQ
        build:
            context: ./meomeo
            dockerfile: Dockerfile
        ports:
            - "80:80"

    backend:
        build:
            context: ./handle
            dockerfile: Dockerfile
        networks:
            - iothub-network

    nginx-backend:
        build:
            context: ./handle
            dockerfile: Dockerfile.nginx
        depends_on:
            - backend
        networks:
            - iothub-network
        ports:
            - "8080:80"
            - "443:443"
        command: nginx -g "daemon off;"
networks:
    iothub-network:
        driver: bridge
